### ISSUE TITLE
Changing the preset of the Superflat worlds

### ISSUE THREAD

**Issue by Teoxex** [MelanX/DefaultWorldType#2]
Hi everyone, I wanted to know some information.
it is possible, after having set the world as "superflat", to put a model of the world in particular as Default
(Example: `minecraft:bedrock,10*minecraft:lava,80*minecraft:clay;minecraft:plains;mineshaft,stronghold(count=10 spread=10),dungeon`)

Ah and I also wanted to know how to put the world superflat by default of course..

**Comment by MelanX** [comment]
You use world type "flat" to create a superflat world. You can see this in `config/defaultworldtype/world-types.txt` where all possibles world types are.
