### ISSUE TITLE
single_biome_surface options

### ISSUE THREAD

**Issue by 5t3v3n** [MelanX/DefaultWorldType#3]
**Is your feature request related to a problem? Please describe.**
for the single_biome_surface world type I do not have the option to select they type of biome for the world

**Describe the solution you'd like**
I would like an option to select the type of biome to make the world

**Describe alternatives you've considered**
Thanks and I enjoy your mod very much

**Comment by MelanX** [comment]
It's too much work in 1.19 to change more than the world preset/type, and I'm not working on older versions anymore.
