### ISSUE TITLE
Strange filename on Linux

### ISSUE THREAD

**Issue by TGurl** [MelanX/DefaultWorldType#4]
Version: defaultworldtype-1.16.3-2.0.2.jar
Minecraft: 1.16.5
Forge: 36.1.61
Default World Type: skyblockbuilder.custom_skyblock 
Modpack: SkyQuesting Updated (a small pack for me and my friends)

**Description**
The mod generates a strange filename on Linux, _defaultworldtype\world-types.txt_. On Linux a forward slash is used to separate directories from filenames. This is not a breaking issue but now there is just a random filename between other config files and the file is not located in the _defaultworldtype_ directory.

**How to reproduce**
1. Install the mod on Linux
2. Check the config directory for the file as stated above

**Expected behavior**
The file _world-types.txt_ is being placed in the correct directory.

**Screenshots**
No screenshots.

**Comment by MelanX** [comment]
Thanks for reporting.
This mod is client only and I recommend using the forge-common.toml to changing the world type in a modpack since 1.16.4. This will also work on servers.
