### ISSUE TITLE
data packs forced on

### ISSUE THREAD

**Issue by redgoblin88** [MelanX/DefaultWorldType#6]
### Minecraft version

1.20.1

### DefaultWorldType version

1.20.1-4.0.3

### Forge version

47.2.0

### The latest.log file

https://pastebin.com/vPgqtHYC

### Issue description

if i have a mod that adds custom resource packs (for example: xycraft override which adds connected textures, by default enabled)
With DefaultWorldType mod in the pack, it prevents me manipulating or dissabling the resource packs (in the example of xycraft, the packs need to go "below" the "vanilla" pack in order to dissable them, but this mod prevents that)

### Steps to reproduce

1. fresh forge install
2. add DefaultWorldType
3. add some mod that has resource packs, for example xycraft override
4. try and "disable" the resource packs from step 3 (in the given example, you "move" them to below the vanilla)
5. note how when you click "done", resource packs do not reload but rather, if you go back to resource packs, they are reset to before you adjusted them

**Comment by MelanX** [comment]
I'm sorry, at the moment I have no idea why this happens. I tried a few things but am not sure why and how to fix it. Will look at it anytime later, sorry.

**Comment by MelanX** [comment]
Wait a second... you really mean resource pack? I always looked at the data packs because that's what the title said. However, I was also able to reproduce it without the mod present.
With resource packs, this mod shouldn't do anything.
